services:
    app.distance_generator:
        class: AppBundle\DistanceGenerator\GoogleDistanceApi
        arguments: ['%google_api_key%']

    app.quote.quote_creator:
        class: AppBundle\Quote\QuoteCreator
        arguments: ['@doctrine.orm.entity_manager', '@app.distance_generator' ]

    app.form.type.job:
        class: AppBundle\Form\Type\JobFormType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }


