services:
    google_direction_api:
        class: AppBundle\DistanceGenerator\GoogleDistanceApi
        arguments: ['%google_api_key%']

    quote_creator:
        class: AppBundle\Quote\QuoteCreator